apiVersion: v1
kind: Service
metadata:
  name: ssm
  namespace: super-simple-mesh
spec:
  selector:
    app: ssm-injector
  ports:
  - protocol: TCP
    port: 8443
    name: ssm-port
    targetPort: 8443
