---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: ssm
webhooks:
  - name: ssm.default.svc.cluster.local
    failurePolicy: Fail
    clientConfig:
      caBundle: ""
      service:
        name: ssm
        port: 8443
        namespace: default
        path: "/"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
        scope:       "Namespaced"
