on:
  pull_request:
    paths:
    - 'controller/*'
  push:
    branch:
    - 'master'
    paths:
    - 'controller/*'

name: Controller Integration
jobs:
  UnitTests:
    if : ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        cd controller && go test ./...

  DockerBuild:
    env:
      IMAGE_NAME: "ssm-injector"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Release Candidate
      if : github.ref != 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: './controller'
        tags: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:rc-${{ github.run_id }}'
    - name: Compute Docker Tag
      id: docker_tag
      uses: ./.github/actions/compute-docker-tag
      with:
        docker_context: './controller'
        image_name: ${{ env.IMAGE_NAME }}
        docker_repo: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Release Tagged Version
      if : github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      with:
        context: './controller'
        push: true
        tags: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.docker_tag.outputs.docker_tag }}'
