on:
  push:
    branch:
    - 'master'
    paths:
    - 'test/*'

name: Mesh Tests
jobs:
  IntegrationTesting:
    if : github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        cd ./test &&  ./e2e.sh
