on: [push, pull_request]
name: Unit Tests
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test controller/...
